name: Maven Tests with Java and RestAssured 

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main  # Replace with your default branch name
  pull_request:
    branches:
      - main  # Replace with your default branch name

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (Maven requires Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Use the same Java version as your project
          distribution: 'temurin'  # Use Temurin (Adoptium) JDK

      # Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Maven local repository path
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}  # Cache key
          restore-keys: |
            maven-${{ runner.os }}-

      # Run Maven tests
      - name: Run Maven tests
        run: mvn test

      # Upload ExtentReports as an artifact (optional)
      - name: Upload ExtentReports
        uses: actions/upload-artifact@v3
        with:
          name: extent-reports
          path: target/extent-reports/  # Path to the ExtentReports directory
          if-no-files-found: warn  # Warn if no files are found
